// 用户信息
export const USERINFO_INIT = 'USERINFO_INIT'
export const USERINFO_UPDATE = 'USERINFO_UPDATE'
export const USERINFO_RESET = 'USERINFO_RESET'
export const USERINFO_ACTION_UPDATE = 'USERINFO_ACTION_UPDATE'

// 系统信息
export const SYSTEM_UPDATE = 'SYSTEM_UPDATE'
